gcp_project_id: "qwiklabs-gcp-03-3e9201f3ade6"

budgets:
  - service: "bigquery.googleapis.com"
    limit: 0.01 # in USD
  - service: "aiplatform.googleapis.com" # Vertex AI
    limit: 0.01 # in USD
  - service: "firestore.googleapis.com"
    limit: 0.01